import type { Metadata } from 'next'
import LeftPane from '@/components/dashboard/LeftPane';
import MainNavbar from '@/components/navbar/MainNavbar';
import Topbar from '@/components/navbar/category/Topbar';
import Bottombar from '@/components/navbar/category/Bottombar';
import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
    title: 'Listings - Dashboard | Buy on Katangwa',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <nav>
                <MainNavbar>
                    <Topbar />
                    <Bottombar />
                </MainNavbar>
            </nav>
            <main>
                <section className="container mx-auto px-3 py-6 grid grid-cols-1 lg:grid-cols-[1.3fr_4fr] lg:px-[60px] lg:gap-x-6">
                    <div className="hidden lg:block">
                        <LeftPane />
                    </div>
                    {children}
                </section>
            </main>
            <footer>
                <Footer />
            </footer>
        </>

    )
}
